### ISSUE TITLE
Could not find a declaration file for module

### ISSUE THREAD

**Issue by cvinothkumar** [jameslnewell/styled-components-breakpoint#15]
TS7016: Could not find a declaration file for module 'styled-components-breakpoint'. 'node_modules/styled-components-breakpoint/dist/cjs/index.js' implicitly has an 'any' type.

**Comment by jameslnewell** [comment]
👋 Hi @cvinothkumar. This library isn't written in Typescript. If you'd like to contribute types to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/) you're most welcome!

Its likely I'll rewrite this library in Typescript at some point as I'm using `typescript` instead of `flowtype` for most of my projects these days, but its not a priority for me at the moment.
